#version 450
#extension GL_EXT_scalar_block_layout : enable
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2 ) in;
#define complex64_t vec2

layout(std430, binding = 0) uniform initData{
    
	int Nl;
	int Nt;
	int Nf;
	int Nw;
	
	float t_min;
	float dt;
	float w_min;
	float dxw;
	
} init_d;

layout(std430, binding = 1) uniform iterData{
    float a;
	float b;
	float c;
} iter_d;


layout(std430, binding = 4) readonly buffer SSBO1 {
   complex64_t S_kl_FT_d[];
};

layout(std430, binding = 5) writeonly buffer SSBO2 {
   complex64_t spectrum_FT_d[];
};


void main() {

    const float pi = 3.141592653589793f;

	uint k = gl_GlobalInvocationID.x;

	if (k >= init_d.Nf) return; //TODO: should be init_d.N_v_FT?

	float w_l = 0.0;
    float mul = 0.0;
    complex64_t res = complex64_t(0.0, 0.0);
    
	float x = k / (2.0 * init_d.Nf * init_d.dt);

	int sk = 1;
	int sl = init_d.Nt;

    for (int l=0; l < init_d.Nw; l++){
		w_l = init_d.w_min * exp(l*init_d.dxw);
		mul = exp(-pi * x * w_l) / init_d.dt;
		res += S_kl_FT_d[l*sl + k*sk] * mul;
	
    }
	spectrum_FT_d[k] = res;
}
